Add table booking page
BeetrootAcademyAccount2/group2-html-css pull request #4
Opened 2024-03-15 13:55 UTC by gretamas

2024-03-15 22:39 UTC, ilona-liashenko commented on pages/book-table.html
> +    <header></header>
looks like it's unnecessary tag here, maybe you just forgot to delete

2024-03-16 09:45 UTC, ilona-liashenko approved these changes

2024-03-16 09:45 UTC, ilona-liashenko commented on pages/book-table.html
> +    <header></header>
looks like header is unnecessary tag here, I suppose you just forgot to delete it

2024-03-16 09:45 UTC, ilona-liashenko commented on pages/book-table.html
> +        <div class="book-table__textarea">
I can be mistaken, but I would recommend to put textfield and button tags inside form tag as this ensures that when the user enters some text to all fields and submits the form by clicking the button, the whole data will be submitted together

2024-03-16 11:28 UTC, lizazp92 commented on pages/book-table.html
> +          <label class="ff-arial f-s36 fw400" for="first name"
I would say the font is super small comparing to the input size

2024-03-16 11:30 UTC, lizazp92 commented on pages/book-table.html
> +          <input
a suggestion to add validation. for example, 'required, max ammount of symbols to each input'

2024-03-16 11:35 UTC, lizazp92 commented on pages/book-table.html
> +            name="first name"
pls check the name attribute. it should not be separated with space if there are 2 words rather a hyphen. 
    "Use lowercase Latin letters.
    Separate different words by a hyphen.
    Do not use periods as well as numbers at the beginning of the name."

2024-03-16 11:39 UTC, lizazp92 commented on pages/book-table.html
> +          <textarea name="Notes" id="" cols="30" rows="10"></textarea>
the id is empty

2024-03-16 11:41 UTC, lizazp92 requested changes
these are suggestions!

2024-03-16 11:43 UTC, lizazp92 commented on pages/book-table.html
> +          <input
I would also say the font (in all inputs) is super small comparing to the input size

2024-03-16 15:12 UTC, gretamas commented on pages/book-table.html
> +        <div class="book-table__textarea">
Thank you Ilona! done

2024-03-17 14:13 UTC, lizazp92 approved these changes

2024-03-17 15:06 UTC, merged